### ISSUE TITLE
firewall policy 10263

### ISSUE THREAD

**Issue by Flock1** [hche11/VGGSound#1]
Hello,

I want to access the dataset and I get this. Can you help me?

<img width="688" alt="Screenshot 2020-05-23 at 12 39 22 PM" src="https://user-images.githubusercontent.com/15093420/82724284-8116df80-9cf2-11ea-9d9d-cf22084caa99.png">

**Comment by WeidiXie** [comment]
here is the link to the dataset:

http://www.robots.ox.ac.uk/~vgg/data/vggsound/

Can you try again ?

**Comment by Flock1** [comment]
Hello,
it works now. Thank you
