### ISSUE TITLE
Pretrained file is damaged

### ISSUE THREAD

**Issue by SCUTCS-WWB** [hche11/VGGSound#10]
Thanks for your great contribution. I try to download "vggsound_avgpool" of model H, but the file is damaged. It is appreciated it if you can upload the file again!

**Comment by hohsiangwu** [comment]
Actually, I found that you can just load the `.tar` model file directly with `torch.load` and it works.
```
checkpoint = torch.load('vggsound_avgpool.pth.tar')
```
